name: reco
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  custom_sliding_segmented_control: ^1.8.3
  dio: ^5.5.0+1
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  exprollable_page_view: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  image_pixels: ^3.0.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  line_icons: ^2.0.3
  loading_animation_widget: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  skeletonizer: ^1.4.1+1
  smooth_page_indicator: ^1.2.0
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
