name: reco
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.1
  google_nav_bar: ^5.0.6
  intl: ^0.19.0
  line_icons: ^2.0.3
  smooth_page_indicator: ^1.2.0
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
